#1
SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME FROM BOOK B, BOOK_AUTHORS A, BOOK_COPIES C WHERE B.BOOK_ID=A.BOOK_ID AND B.BOOK_ID=C.BOOK_ID;
#2
SELECT CARD_NO, COUNT(*) FROM BOOK_LENDING WHERE DATE_OUT BETWEEN '2017-01-01' AND '2017-07-01' GROUP BY CARD_NO HAVING CARD_NO >3;
#3
SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME FROM BOOK B, BOOK_AUTHORS A, BOOK_COPIES C WHERE B.BOOK_ID=C.BOOK_ID AND c.NO_OF_COPIES = 1;
#4
SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME FROM BOOK B, BOOK_AUTHORS A, BOOK_COPIES C WHERE B.BOOK_ID=A.BOOK_ID AND B.BOOK_ID=C.BOOK_ID AND b.TITLE LIKE 'A%' AND c.NO_OF_COPIES > 2;
#5
SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME, C.* FROM BOOK B, BOOK_AUTHORS A, BOOK_LENDING C GROUP BY CARD_NO HAVING COUNT(DISTINCT CARD_NO > 1);
#6
UPDATE book SET TITLE = REPLACE (TITLE, 'DBMS', 'DATABASE MANAGEMENT SYSTEM') WHERE BOOK_ID = 1;
#7
DELETE FROM BOOK WHERE BOOK_ID=3;
#8
CREATE VIEW V_BOOKS AS SELECT B.BOOK_ID, B.TITLE, C.NO_OF_COPIES FROM BOOK B, BOOK_COPIES C, LIBRARY_BRANCH L WHERE B.BOOK_ID=C.BOOK_ID AND C.BRANCH_ID=L.BRANCH_ID;